### ISSUE TITLE
spk pack: cannot allocate memory

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#10]
Hey @zarvox,

When I'm trying to build my Paperwork SPK after a while the error shown below appears. I checked two things so far:
- just adding more resources to the VM doesn't help
- this seems not to be a sole vagrant-spk issues (spk pack works with e.g. the php test app)

Have you tried building an spk? 

```
$ vagrant-spk pack paperwork.spk
paperwork.spk
Calling 'vagrant' 'ssh' '-c' 'spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk' in /Development/paperwork/.sandstorm
*** Uncaught exception ***
sandstorm/util.c++:47: overloaded: open(name.cStr(), flags, mode): Cannot allocate memory; name = /opt/app/frontend/node_modules/gulp-livereload/node_modules/debug/debug.js
stack: 0x42b8c5 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42965e 0x427f2a 0x427e7d 0x4bffd1 0x4c0c55
Connection to 127.0.0.1 closed.
Traceback (most recent call last):
  File "/Development/vagrant-spk/vagrant-spk", line 544, in <module>
    main()
  File "/Development/vagrant-spk/vagrant-spk", line 541, in main
    operation(args)
  File "/Development/vagrant-spk/vagrant-spk", line 506, in pack
    call_vagrant_command(sandstorm_dir, "ssh", "-c", "spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk")
  File "/Development/vagrant-spk/vagrant-spk", line 417, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'ssh', '-c', 'spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk']' returned non-zero exit status 1
```

**Comment by zarvox** [comment]
Hmmm.  I just did the following successfully:

```bash
git clone https://github.com/JamborJan/paperwork
cd paperwork
# modify .sandstorm/pkgdef.capnp with a new package id
# since I don't have your signing keys
vagrant-spk dev
# verify that paperwork runs
vagrant-spk pack paperwork.spk
```

And this correctly produced a 61MB spk.

My VMs are by default allocated 4GB of RAM, but I watched the spk pack and it looked like the VM never used more than ~300MB.  So I'm surprised that this is failing for you.

Perhaps try cleaning your repo/VM?  `vagrant-spk destroy` will blow away the VM, but not your Vagrantfile/scripts, and then you can `vagrant-spk up` and get a clean VM.

**Comment by JamborJan** [comment]
I did all that already, including destroying it or assigning more resources to the VM and I did it now again with the same result.

Then I thought: What would happen if app id and key are not matching?

I had a different machine before where I ran the build and I exported the key with ```spk getkey appid > app.key```and copied this file to the ```.sandstorm``` folder of my user on the new dev machine.

That should not be the reason as I also tried to pack the app with a complete new id and key pair which also didn't work.

As I can pack other apps, I made a test with the php demo app. It seems I either find strange situations or do strange things myself...

**Comment by zarvox** [comment]
Hmmm, that's quite odd!

Perhaps you have something weird in your paperwork/ git tree, which causes issues on your machine, but leaves mine alone?  Maybe it's .gitignore'd, or just not checked in to the repo?  That might explain why it's repeatedly causing you issues when you create new VMs, but not affecting me.

Perhaps try cloning the repo to a pristine folder, and trying a new VM in that folder?

**Comment by JamborJan** [comment]
So now I deleted everything from my dev machine, the whole repo and also the vagrant-spk repo. I even did restart the machine. But still ...

```bash
paperwork JJ$ vagrant-spk pack paperwork.spk
paperwork.spk
Calling 'vagrant' 'ssh' '-c' 'cd /opt/app/.sandstorm/ && spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk && mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk' in /Users/JJ/Development/paperwork/.sandstorm
*** Uncaught exception ***
sandstorm/util.c++:47: overloaded: open(name.cStr(), flags, mode): Cannot allocate memory; name = /opt/app/frontend/node_modules/gulp-livereload/node_modules/gulp-util/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex/readme.md
stack: 0x42b8c5 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42965e 0x427f2a 0x427e7d
Connection to 127.0.0.1 closed.
Traceback (most recent call last):
  File "/Users/JJ/Development/vagrant-spk/vagrant-spk", line 556, in <module>
    main()
  File "/Users/JJ/Development/vagrant-spk/vagrant-spk", line 553, in main
    operation(args)
  File "/Users/JJ/Development/vagrant-spk/vagrant-spk", line 513, in pack
    "mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk"
  File "/Users/JJ/Development/vagrant-spk/vagrant-spk", line 417, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'ssh', '-c', 'cd /opt/app/.sandstorm/ && spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk && mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk']' returned non-zero exit status 1
paperwork JJ$ 
```
I also work on 2 machines with exactly the same error.
```
sandstorm/util.c++:47: overloaded: open(name.cStr(), flags, mode): Cannot allocate memory; name = /opt/app/frontend/node_modules/gulp-livereload/node_modules/gulp-util/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex/readme.md
stack: 0x42b8c5 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42b81d 0x42b38b 0x42965e 0x427f2a 0x427e7d
```
Before I deleted everything and started from scratch the mentioned file after ```Cannot allocate memory; name =``` was different (see first posting here). Super odd.

I'm running
- Mac OS X 10.10.3
- VirtualBox 4.3.26r98988
- Vagrant 1.7.2

I will poke around this more to find out what happened here. If anyone has an idea I'm more than happy to hear it.

**Comment by paulproteus** [comment]
`cannot allocate memory` suggests that there isn't enough RAM etc. to do a `malloc`.

@zarvox it seems to me the `vagrant-spk` VM needs swap and doesn't have any.

To test this theory, @JamborJan , you could do:

```
vagrant ssh
sudo dd if=/dev/zero of=/root/swap.img bs=1M count=1024
sudo mkswap /root/swap.img
sudo swapon /root/swap.img
```

and then retry the command.

**Comment by paulproteus** [comment]
Similarly, you could try:

```
vagrant ssh
sudo service sandstorm stop
```

and then retry the `vagrant-spk pack` command.

**Comment by JamborJan** [comment]
@paulproteus both suggestions didn't change anything about the result. Same error and same duration until it appears.

**Comment by zarvox** [comment]
Okay, thanks to @jparyani (who has a MacBook Pro), I was able to reproduce this.

My current guess is that it's an issue with VirtualBox's shared folder subsystem that only allows a limited number of files from the host to be `open()`ed or `mmap()`ed at a time from the guest.  At present, `spk pack` will `open()` each file, `mmap()` it, and then `close()` it.  Eventually, a bit past 4096 files, the open() returns -ENOMEM.

I'll test this out with VirtualBox on Linux to see if it's an issue in the host code for OSX or the guest code for Linux, and to see where we can go from there.  I've been using the vagrant-libvirt backend with the 9p shared filesystem and expected that they'd work equally well, but it appears that might not be the case.

Another option you could try in the meantime is switching the `synced_folder` type in the `Vagrantfile` to `nfs` to see if that will handle more mmaps.  I haven't actually tried this, but it's another synced folder backend that should work on OSX.

```diff
-  config.vm.synced_folder "..", "/vagrant"
-  config.vm.synced_folder "..", "/opt/app"
+  config.vm.synced_folder "..", "/vagrant", type: "nfs"
+  config.vm.synced_folder "..", "/opt/app", type: "nfs"
```

**Comment by JamborJan** [comment]
This at least explains the behavior. Unfortunately ```nfs```requires a private host only network. I didn't find out how to add a second network to the vagrant VM so far, so I tested it with:

```diff
- config.vm.network :forwarded_port, guest: 6080, host: 6080
+ config.vm.network :private_network, ip: "33.33.33.33"
```
And it worked. Of course it is a workaround for now to ```vagrant halt```, switch network and ```vagrant up``` again to build a package but I think we are also pretty close to the final solution here.

What is you preferred solution @zarvox ? Should I make more tests to get a second network running with the private network or do you implement a different way of handling shared folders and we close this issue with the workaround in place waiting for a change in ```vagrant-spk```?

**Comment by paulproteus** [comment]
To get a host-only network, I recommend the following:

  # Create a link-local private address, so that the host can
  # use NFS with the Virtualbox guest. Virtualbox/Vagrant handles
  # network address translation so outbound network requests still
  # work.
  #
  # We pick the 169.254.253.2 address because it is similar to,
  # but different from, the IP address used by Sandstorm's
  # own Vagrantfile's host-only network.
  config.vm.network :private_network, ip: "169.254.253.2"

​
I think in the long run, it'll be nice to fix "spk" to not trigger this
problem; I suggest adding the above workaround to your Vagrantfile until
then, which I estimate at 1-14 days.

**Comment by zarvox** [comment]
@JamborJan With @paulproteus's suggestion, you should be able to have multiple `config.vm.network` stanzas at a time in the Vagrantfile, which will let you have both forwarded ports and NFS.

See the Sandstorm Vagrantfile for an example of this: https://github.com/sandstorm-io/sandstorm/blob/ad0be9947546848264266e3942f3e6d73a4b03e6/Vagrantfile#L14-23

I suggest you add the network line Asheesh suggested to the Vagrantfile and use that to get paperwork working for now, and I'll make a similar change for what `vagrant-spk` generates in short order.

I'm not sure how easy it'll be to make `spk` not mmap all the files; my impression from a first glance at the code is that this is how capnproto's lazy packing works (provide all maps up front to builder object, then build), but I'll see if there's anything we can improve here.

**Comment by JamborJan** [comment]
Thx @paulproteus & @zarvox
