### ISSUE TITLE
/var/storage wiped out in launcher.sh?

### ISSUE THREAD

**Issue by zarvox** [JamborJan/paperwork#11]
It seems like in `.sandstorm/launcher.sh` you remove the existing `/var/storage` folder.

This might not be what you want when resuming existing grains if any user data or attachments get stored there - you'd wind up deleting all such data as soon as the user closes and launches the grain again.

Does paperwork store anything of importance in /var/storage, or can it all be safely thrown away every run?

**Comment by JamborJan** [comment]
This seems to be something left over from all the testing to get vagrant-spk running. There have been so many different options where, when, how to move the folder that I needed that for testing.

I will check it out in detail and fix it. 

Thanks for noticing.

**Comment by JamborJan** [comment]
Hi @zarvox 

I used that wipe out during testing to ensure to have always a clear status when a grain is started. It seems to have no effect at the moment as I can create more notes and attachments and they always stay as they are even after closing a grain and restarting it.

It seems that the deletion and recreation of the structure happens before the grains data is there.

What is your opinion on that: keep it or remove the ```rm -rf /var/storage```?

I'm not sure if it either ensures a clear situation when a grain start (= keep it) or if it might cause issues later when starting a grain might change and it causes confusion then (=remove it).

**Comment by JamborJan** [comment]
Any idea if it's better to keep or to remove the ```rm -rf /var/storage``` @zarvox ?

I'm not sure if it either ensures a clear situation when a grain start (= keep it) or if it might cause issues later when starting a grain might change and it causes confusion then (=remove it).

**Comment by zarvox** [comment]
Opinion: leave the `rm -rf /var/storage` in `build.sh` and remove it from `launcher.sh`.  Keep all the `mkdir -p` calls in `launcher.sh`, so it's safe for both first-run and subsequent runs.

Rationale: outside of Sandstorm, the app already has to be able to handle data in that folder across requests, or if php5-fpm is reloaded, or whatnot.  If it turns out paperwork is better off with `/var/storage` removed (I suspect it won't matter either way), we can delete data later.  The converse is not true - if we've deleted data and it turns out to have been important, that's bad.

Finally, if in the fullness of time, we think that /var/storage *should* be transient, maybe we should link it to a tmpfs (link to `/tmp/storage`) instead of to persistent storage (`/var/storage`).

**Comment by JamborJan** [comment]
Moving ```storage``` to ```/tmp``` is not working out. Attached files to notes get lost in that case. Implementing the suggestion option works as far as I can say after testing it a bit.

**Comment by zarvox** [comment]
Ahhh, sounds like leaving the `rm -rf storage` in `launcher.sh` would probably also have wiped out files attached to notes as well, then.  I'm glad I filed this ticket!

So we've answered the question "is there important user data in `/var/storage`" and the answer is "yes" so we should make sure to preserve it between runs, which is precisely what you implemented.  Awesome!
