### ISSUE TITLE
Upgrading old grains to new app version

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#13]
After having moved from the docker build process to ```vagrant-spk``` I can perfectly create new grains but cannot open existing ones which have been created with the older version of the app. 

It's pretty obvious that the reason is the mysql setup. 

I have used the recommended setup back then like it was used here: https://github.com/jparyani/Lychee/blob/sandstorm/Dockerfile#L30-L33

Just in case you see the reason of the issue @zarvox you might point me to it (I must really bother you these days .... :-) ). I will also continue to work on that but after having some other stuff accomplished first for the paperwork package.

This is the sandstorm log.

```

** SANDSTORM SUPERVISOR: Starting up grain.
Installing MySQL system tables...
150612 10:53:03 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150612 10:53:03 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0ubuntu0.14.04.1) starting as process 37 ...
OK
Filling help tables...
150612 10:53:03 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150612 10:53:03 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0ubuntu0.14.04.1) starting as process 43 ...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER !
To do so, start the server, then issue the following commands:

/usr/bin/mysqladmin -u root password 'new-password'
/usr/bin/mysqladmin -u root -h sandbox password 'new-password'

Alternatively you can run:
/usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the manual for more instructions.

You can start the MySQL daemon with:
cd /usr ; /usr/bin/mysqld_safe &

You can test the MySQL daemon with mysql-test-run.pl
cd /usr/mysql-test ; perl mysql-test-run.pl

Please report any problems at http://bugs.mysql.com/

/opt/app/.sandstorm/launcher.sh: line 31: /etc/mysql/conf.d/small.cnf: Read-only file system
sed: can't read /etc/mysql/debian.cnf: Input/output error
sed: couldn't open temporary file /etc/mysql/sedt6PN2I: Read-only file system
Neither host 'sandbox' nor 'localhost' could be looked up with
/usr/bin/resolveip
Please configure the 'hostname' command to return a correct
hostname.
If you want to solve this at a later stage, restart this script
with the --force option
chown: invalid spec: 'mysql:'
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
150612 10:53:04 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150612 10:53:04 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0ubuntu0.14.04.1) starting as process 68 ...
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
[...] 

```

**Comment by JamborJan** [comment]
Can only be tested when https://github.com/JamborJan/paperwork/issues/18 is done.

**Comment by JamborJan** [comment]
Hi @zarvox,

Now that I have finalized the new version of the paperwork app I come back to this issue.

Unfortunately I cannot upgrade my old app which has been created from a Docker container with the new version which has been created with vagrant.spk.

I used this Dockerfile to setup the system: https://github.com/JamborJan/paperwork/blob/4e0666e3705cc69cccf41e4c0b1fb70014b44c0d/Dockerfile

Now I use ```vagrant-spk```. I guess it has something to do with the way how mysql was set up in the Docker-container but didn't find out so far what. If you have any idea or see where a cause might be from your experience, I would appreciate a hint where to look further to get the old grains updated.

Thanks!
JJ

**Comment by paulproteus** [comment]
Hey @JamborJan . @zarvox is away for the week, so maybe I can work with you on debugging this.

For what it's worth, I agree that MySQL is likely the culprit here. Probably `vagrant-spk` should have support for migration scripts, so that you can check for this condition and do a migration.

**Comment by JamborJan** [comment]
I think the script is no big deal (maybe I am wrong).

The most important thing for me now: get an idea what the cause is. I'm kind of looking at the stuff and am not seeing it. If you could help with that it would be awesome. I will try to find out on my own, but it might take some time.

**Comment by JamborJan** [comment]
I'm not that sure that mysql is the issue.  In ```data/log/nginx/error.log``` I find the following. The nginx config in the old Docker container was: https://github.com/JamborJan/paperwork/blob/4e0666e3705cc69cccf41e4c0b1fb70014b44c0d/nginx.conf

In the new nginx conf there is still an "example.com" which doesn't seem to hurt when creating new grains. Also switching this e.g. to 127.0.0.1 doesn't help. 

I'm done for today, will work tomorrow again on that. If you have any input @paulproteus let me know.

```
2015/07/20 20:12:51 [error] 78#0: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Illuminate\Database\QueryException' not found in /opt/app/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 625" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xmn1486iyrvs9seydeyq.pandorica.centur.io:7443"
2015/07/20 20:21:11 [error] 78#0: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Illuminate\Database\QueryException' not found in /opt/app/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 625" while reading response header from upstream, client: 127.0.0.1, server: example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "jygp89g3yrz4fqa8jqxg.pandorica.centur.io:7443"
```

**Comment by paulproteus** [comment]
Hi JJ! Still need help with this? I can see what I can do shortly.

**Comment by JamborJan** [comment]
Hi, help is still appreciated. I'm working a lot these days to get it proper done. Now everything besides the update of old grains should work as expected.

Not sure if we can say: sorry guys update is not possible. I also don't know how many people are already using the package (do you see that in the app store?).

**Comment by JamborJan** [comment]
The things I see so far:

The environment seems to be pretty different set up. When you create an empty old grain with the old app version and a new one you see the differences in the backups. For example when you look into ```data/log```.

When you upgrade an old grain you will get now an error message and find one error in the nginx log. More I didn't find so far. Sorry for being not so useful here, this seems to be out of my scope at the moment and takes some time to get it ...

![bildschirmfoto 2015-07-23 um 08 58 15](https://cloud.githubusercontent.com/assets/7508960/8844766/06d0b696-3119-11e5-8ed6-9b947377aba7.png)

![bildschirmfoto_2015-07-23_um_09_00_06](https://cloud.githubusercontent.com/assets/7508960/8844791/4c680042-3119-11e5-9e40-14e5a02d35d9.png)

**Comment by JamborJan** [comment]
Current status:

The basic MySQL setup seems to be okay. When I access an old grain restored to a new app or a fresh created one I can do the following successful with both:
- Start Sandstorm in a Vagrant Box
- Upload a package of the app
- Upload a the grain backup which is broken & needs to be analyzed OR create a new grain
- Start the grain and keep it running
- No vagrant-spk dev required here
- vagrant-spk ssh
- sudo -i
- mysql -u root --socket /opt/sandstorm/var/sandstorm/grains/{GRAIN_ID}/sandbox/run/mysqld/mysqld.sock
- mysql> show databases;
- mysql> use paperwork;
- mysql> show tables;
- mysql> select * from user;

So I can access in both cases with 100% the same process and without any issues the database.

The shown error message from the Laravel Framework is not that helpful and should show more details as advertised in the error message itself. See https://github.com/laravel/framework/issues/9755 for more details here.

**Comment by JamborJan** [comment]
The used version of the Laravel Framework seems to be EOL so they are not helping with the wrong error message. An update of the used Laravel Framework in Paperwork is discussed here: https://github.com/twostairs/paperwork/issues/54

**Comment by JamborJan** [comment]
After having fixed a bug in the old / eol laravel ramework I now get a proper error message which indicates that a update script from paperwork has not been run when starting a new grain.

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paperwork.sessions' doesn't exist (SQL: select * from `sessions` where `id` = d72a01c44e32f26bdc49f5ce9f1be87507bbef69 limit 1) 
```
I will continue working on that. Seems like the chance of getting this solved slightly improved.

**Comment by paulproteus** [comment]
Wow! Good spotting!

**Comment by JamborJan** [comment]
Unfortunately I have a kind of a messed up situation with the upgrade scripts from Paperwork. Parts are working and then it crashes. They have some kind of role back but that isn't working properly. So you always have to restore a backup for a new test. And the really annoying thing here is: I cannot restore a backup in ```vagrant-spk dev``` mode. It always says error 200 grains app not installed and gives me the exact ID from the app I am running in dev mode.

So this takes a while mainly because of try error, roll back, restore, try again ... etc.

**Comment by JamborJan** [comment]
First improvements done: https://github.com/JamborJan/paperwork/commit/bb4f3999cb256f1cb91f38fc9b8beba4b3fdc572

Update script still not working but my Sandstorm specific stuff should now be ready for upgrades as soon as I figured out how to run the update scripts.

**Comment by JamborJan** [comment]
Booja!!! ... getting close. The root cause is a unstable update script. I re-created it manually step by step and all ```ALTER TABLE``` statements for new ```CONSTRAINT FOREIGN KEY``` fail with:

```
ERROR 1005 (HY000) at line 16: Can't create table 'paperwork.#sql-3a_46' (errno: 150)
```
When I go through the rest manually. I can finally bring up an old grain in the new app. It also counts correct the notes in the database etc. but due to the wrong foreign keys it doesn't display anything.

So far so good, more tomorrow.

FYI my test sql update script (not working completely yet): https://gist.github.com/JamborJan/66c3bfb425c82a646f36

![bildschirmfoto 2015-07-28 um 20 43 07](https://cloud.githubusercontent.com/assets/7508960/8940457/991865a0-3559-11e5-8f2c-c5d65be50b8e.png)

**Comment by JamborJan** [comment]
Waiting for feedback from the Paperwork devs: https://github.com/twostairs/paperwork/issues/462

**Comment by JamborJan** [comment]
I made some progress here with the following process:
- detect if you are starting an old grain or new
- if new: start up and everything is fine
- if old: display an export page
- user exports data
- closes grain
- imports data again in new grain

There are still some scenarios where errors are displayed so this should not be used so far.

**Comment by JamborJan** [comment]
Finally I have been able to implement a migration workaround:
- Update your app to the latest version
- Start an old grain, you will see the export screen with additional information
- Follow the steps shown on the screen and import the data in a fresh grain

![untitled](https://cloud.githubusercontent.com/assets/7508960/9078440/a3325b78-3b3e-11e5-8f3a-928ae2d3a67d.gif)
