### ISSUE TITLE
"File > New collection" does nothing

### ISSUE THREAD

**Issue by erikmaarten** [JamborJan/paperwork#15]
When pressing "New collection" in the File menu, the menu closes without giving any indication that something has happened. No new collection is created.

The Sandstorm log shows no error.

If this action is intentionally removed from Paperwork in order to fit better with the Sandstorm grain model, perhaps the menu option could be removed altogether.

![paperwork_menu](https://cloud.githubusercontent.com/assets/4586719/8680286/9fe1aecc-2a60-11e5-9505-e0abcd3f39b1.png)

**Comment by JamborJan** [comment]
Thanks for reporting this issue. I will check it in more detail and fix it in the next version.

**Comment by JamborJan** [comment]
The next version might take some time as the sandstorm platform and the spk is improving and this causes some additional work from time to time. Thanks for your patience.

**Comment by erikmaarten** [comment]
Great! The issue isn't very severe, it just adds a little bit of confusion, so no worries if next release takes a while.

**Comment by JamborJan** [comment]
FYI @erikmaarten 

This seems to be an issue also upstream. Will fix it tomorrow, either by really fixing it or removing, don't know so far why we need it here.

**Comment by JamborJan** [comment]
I have no idea what collections are for in paperwork. There are also some issues reported that th button is not working in the upstream repository:
https://github.com/twostairs/paperwork/issues/364
https://github.com/twostairs/paperwork/issues/352
https://github.com/twostairs/paperwork/issues/318
https://github.com/twostairs/paperwork/issues/15

For now I think the best thing is to remove the button when in Sandstorm mode.
