### ISSUE TITLE
Edit notes: empty editor

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#21]
Reported here: https://groups.google.com/forum/#!topic/sandstorm-dev/ObdnUs2vyrU

[..]
Also, I had a problem where the text of a Paperwork note wouldn't appear in the editor. I'm attaching an animated GIF screencast; ignore the first couple of seconds; the problem should be clear by the end of the screencast.
[...]
![anim](https://cloud.githubusercontent.com/assets/7508960/8844304/e9a122b8-3113-11e5-86a4-2b23d7425875.gif)

**Comment by JamborJan** [comment]
Hey @paulproteus,

I have tested a thousand different grains with Firefox 41 and Safari on a Mac with OS X 10.10.4 and I don't get this issue. Can you provide any more details?

Off topic question: how do you create these gif screen recordings?

**Comment by paulproteus** [comment]
I do see a few errors in the console:

```
https://alpha-q0qlinlz27r7vaijibre.sandstorm.io/css/mathquill.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://alpha-q0qlinlz27r7vaijibre.sandstorm.io/images/navbar-logo@2x.png Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://alpha-q0qlinlz27r7vaijibre.sandstorm.io/ckeditor/skins/bootstrapck/editor.css?t=EAPE Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js:913 Detecting changes using MutationObservers
https://alpha-q0qlinlz27r7vaijibre.sandstorm.io/css/mathquill.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://alpha-q0qlinlz27r7vaijibre.sandstorm.io/ckeditor/skins/bootstrapck/editor.css?t=EAPE Failed to load resource: the server responded with a status of 404 (Not Found)
```

I'm using Chromium on Debian.

I don't really think that CSS being missing would cause these problems, though. Maybe I'm using an old version of the SPK. What's the current SPK URL?

**Comment by JamborJan** [comment]
You can find the latest pre-release here on github: https://github.com/JamborJan/paperwork/releases/download/V5/paperwork.spk.zip

Database migration still not working, root cause identified: error by design, the paperwork team didn't take care so far that the database is migrate-able easy and introduced UUIDs without migration scripts.

**Comment by paulproteus** [comment]
Thanks for the SPK URL. I just did a fresh upload and seem to have the same
problem.
https://alpha.sandstorm.io/shared/eropKuDWTeHImVf9RmoEgisCXSAqdFPc3c9RSHUveRD
is a sharing link; do you see it too?

re: migrations: I read the through upstream discussion. Seems like they're
sad about the current situation, too. If you want to try writing migration
scripts that work for people, cool. But if you get far enough in that and
conclude it's not worthwhile, then make a new appId and let that be that.
We'll all be sad, but I guess we'll move on.

**Comment by JamborJan** [comment]
The link works and I can also see the text in edit mode. But I now realize that the font is kind of strange...
Maybe this and the errors mentioned by you earlier are linked together and cause the not visible edit field in some situations. I will keep this open and investigate more + solve it of course :-)

![bildschirmfoto 2015-07-29 um 20 14 46](https://cloud.githubusercontent.com/assets/7508960/8965880/94b93d4c-362e-11e5-8f72-4dc747c5708b.png)

**Comment by JamborJan** [comment]
Hey @paulproteus can you please test again with the version which is available in the sandstorm app store. I tryed to reproduce the issue in several ways but never was able to.

Thanks!

**Comment by JamborJan** [comment]
Hey @paulproteus, I have not been able to reproduce this issue and also no other users have reported something like this so far. 

So unfortunately without your help I'm not able to do anything here. 

I close the issue now. Feel free to re-open it or open a new one when you discover any further issues. 

FYI: a new release will be made during the next days / weeks with more bug fixes.
