### ISSUE TITLE
make import robust against special characters in title

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#27]
See also https://github.com/twostairs/paperwork/issues/484

Work around if you have import issues:
- open the xml and replace ```&nbsp;``` by a normal space
- replace & < > in the titles by the html encoded versions (BUT only titles not the note body as this is already ok)

**Comment by erikmaarten** [comment]
Had this problem, but part of the problem seems to be that Paperwork V4 exports don't actually export UTF-8 text (even though it says the encoding is UTF-8). In my case, I had "&auml;" in the title, which should have been "ä". I replaced the encoded version with "ä" and import worked.

**Comment by JamborJan** [comment]
Okay then I guess we also have the issue with ö ü ß and so on. Thx for your feedback! Will check and try to fix that.

**Comment by JamborJan** [comment]
The issue has been solved. See https://github.com/JamborJan/paperwork/releases/tag/V7 or update via Sandstorm App Store.
