### ISSUE TITLE
Misspelling of encoding in exports -- seems fine but could it cause trouble?

### ISSUE THREAD

**Issue by erikmaarten** [JamborJan/paperwork#29]
While looking through a .enex exported file from Paperwork V4, I stumbled on the following where "encoding" has become "enconding":

    <data enconding="base64">

It doesn't seem to be a problem in this case, I was able to import the file, including the image, but I thought I'd just point it out in case it could cause future problems.

**Comment by JamborJan** [comment]
Thanks, I fixed it.
