### ISSUE TITLE
Notebook created on import behaves differently from regular notebooks

### ISSUE THREAD

**Issue by erikmaarten** [JamborJan/paperwork#30]
Import a V4-exported file, then:

- Select a note that is not in the automatically created Evernote folder
- Choose Edit > Move note

In the list of notebooks that the note can be moved to, the Evernote folder created on import will not show up (regardless of whether it has since been renamed or not)

**Comment by JamborJan** [comment]
Thanks for the feedback. I will check that in detail. Maybe it is a desired feature from the upstream authors but I'm not sure why this should be.

**Comment by JamborJan** [comment]
Hi @erikmaarten 

I made a test:
- create a new grain of paperwork
- I named the initial note "test issue 30", this one is located in the welcome notebook
- I imported a test ENEX file with 2 notes
- The Evernote folder is created
- I can move the initial note to this folder

My second test was with an new created note and I also was able to move that one.

My 3rd test was renaming the notebook, this also worked.

During my test I have seen a scenario which maybe causes confusion - at least I felt a bit confused while testing. The move note dialog doesn't show the notebook the note is saved in before moving. While doing tests moving the note I got confused which notebook is now source and which destination.

Can you please check again and maybe send some more details when you still have the same issue?

Here a visual summary of one test:
![untitled](https://cloud.githubusercontent.com/assets/7508960/9680767/804346ea-52f9-11e5-86f5-5fbe7c8c5370.gif)

**Comment by erikmaarten** [comment]
Have checked this again now, and it seems I didn't realize the notes I were trying to move were already in the folder I was intending to move to. Should have checked more carefully... No bug here!

**Comment by JamborJan** [comment]
Thanks for your feedback. Let me know if you find any other things or if you have any questions.

JJ
