### ISSUE TITLE
Auto-save relies on localStorage

### ISSUE THREAD

**Issue by kentonv** [JamborJan/paperwork#32]
Hi Jan,

A user reported that the "auto save" feature doesn't work. (A few moments after editing a note, the words "auto saved" appear under the edit window.)

From what I can tell, this feature often doesn't work upstream either -- most of the time, it does not offer to restore the auto-saves (see upstream issue 508). But, when it does work, it's based on localStorage, which means it definitely won't work after starting a fresh Sandstorm session.

Seems like a good idea to either disable the feature (so that people don't get a false sense of security from it) or change it to replicate localStorage back to the server. You can look at how Jason did this with Laverna, for example.

**Comment by JamborJan** [comment]
Thx Kenton, will check that and try to find an appropriate solution. Hopefully with the feature enabled.

**Comment by JamborJan** [comment]
Postponed the feature to a future release.

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
