### ISSUE TITLE
How does the QR code work?

### ISSUE THREAD

**Issue by ovizii** [JamborJan/paperwork#35]
Open a notebook => Settings => Client => QR Code

Below the code it says: Scan this QR code with your mobile app to auto-configure your Paperwork account. 

If I scan the code, I don't seem to have the right app to open it with. Is there a paperwork android client somewhere?

**Comment by JamborJan** [comment]
@liongold can you help with an answer / info here? 

I'm currently on vacation and cannot check in detail. I was only able to find something here: https://github.com/twostairs/paperwork/issues/379

Maybe that helps a bit.

**Comment by ovizii** [comment]
no rush.Thanks for the link to the discussion about the android app but that still leaves the question of what the purpose of that QR code is :-)

**Comment by JamborJan** [comment]
The QR code contains the connection information, e.g. like this:

```
{"paperwork":{"user":{"username":"sandstorm_admin","firstname":"sandstorm_admin","lastname":" ","language":"en"},"access":{"external":{"dns":"https:\something.your.server.com","ports":{"http":8000,"https":8000,"forceHttps":true}},"internal":{"dns":"localhost","ports":{"http":8888,"https":8443,"forceHttps":false}}}}}
```

I guess "the app" should be able to read that via the build in camera and then automatically connect to the instance. But I never used an app and I don't know if the link I've provided is a link to "that app" which can do that. Sorry that I have not more infos so far, maybe @liongold can help us here. He is a good experienced paperwork maintainer.

**Comment by ovizii** [comment]
I had seen that but something isn't right here, my scanning app decodes it ias "type text". If I scan another working QR code I get: type URL". 

Also, the link contains ports which I am not using, my sandstorm instance runs on port 443, are those hard-coded? 

Let's see maybe someone else can eventually clarify this. Not an urgent issue though.

**Comment by JamborJan** [comment]
Hi @ovizii , I'm have been in contact with the upstream authors of Paperwork. So far I can say that there are plans to build a Paperwork V2 which includes apps for most used mobile platforms.

At the moment I have not found a working app so far for iOS. For android I found this beta version: https://github.com/theSoenke/Paperwork-Android. I'm not able to test this so far.

Sorry for not having a better answer so far. As I cannot do anything here, would you mind when I close the issue?
