### ISSUE TITLE
Sandstorm/sandcats toolbar button invisible

### ISSUE THREAD

**Issue by blutux** [JamborJan/paperwork#36]
Hi,

I've just install paperwork on the sandstorm project. I've discover paperwork by this way and it's look very amazing. I'm very exciting to try it. However, when i try to create or edit a note, I open the toolbar when I'm clicking on the arrow. But all the icons are blanks and not visible.

Could you help me ? Am I at the right place ?

Thanks in advance

Blutux

**Comment by JamborJan** [comment]
Hi, you are definitely at the right place. Would you mind to attach a screenshot? I will take a look at this.

**Comment by blutux** [comment]
You can find the screenshot here [screenshot](http://i.imgur.com/EJTd19T.png)

**Comment by JamborJan** [comment]
Hi @blutux unfortunately I'm not able to reproduce the issue. I checked with different browsers, configs, blockers, and also TOR and it always worked for me. Can you send some more details about your configuration please?

- Are you using oasis.sandstorm.io or an own setup?
- Which browser are you using?
- Are there any add-ons you use with your browser?

Thanks a lot for helping to track down this issue!

JJ 

FYI: in some scenarios I don't see some fonts like shown in the example below, the editor buttons are always there.

![bildschirmfoto 2016-01-30 um 15 05 45](https://cloud.githubusercontent.com/assets/7508960/12696160/11f032aa-c763-11e5-953c-f437802d406a.png)

**Comment by blutux** [comment]
Hi @JamborJan I use my own setup, i have tried with safari, chrome and firefox. And i have always the bug. I have tried also on oasis.sandstorm.io and I always have the bug (i have tried only with chrome on oasis).

FYI : i'm on OS X Yosemite 10.10.5, i have no ideo if the Operating System could have an influence on the issue, if i have time tomorrow, i will try on windows. And I will tell you my feedback.

Thanks for the help.

Blutux

**Comment by blutux** [comment]
.... i'm disappointed ... it's works on my mother mac (os x El Captain) and on my brother pc (Windows 10). So i have tried to update my mac to El Captain. And Still not working  (i have tried with Safari, firefox and chrome). I don't know what i can do now :(

**Comment by JamborJan** [comment]
Hi @blutux I was thinking about possible reasons. One could be 3rd party apps like blockers but this would mean you have them in all browsers on your computer which is pretty unlikely.

We could get some more information for debugging when you take a look at the console. Please follow the instructions below to do so. The example is done in Safari but should be pretty much the same for all browsers you are using. Please ensure to have the console open before opening the grain and then the note. If you have some CSS warnings like shown in the image below it's okay. If there are errors we are a step closer. :-)

Thanks for your help tracking this issue down!

JJ

![bildschirmfoto_2016-02-01_um_06_33_16](https://cloud.githubusercontent.com/assets/7508960/12709667/8c804838-c8ae-11e5-868f-ef1715f5d2d7.png)

**Comment by blutux** [comment]
Apparently i can't load the @2x images (yes i have a retina macbook pro with retina screen :p )<img width="724" alt="screenshot 2016-02-01" src="https://cloud.githubusercontent.com/assets/4017432/12710785/3acf6724-c8ba-11e5-8c14-086cfb4d2006.png">

**Comment by JamborJan** [comment]
Yay! We found the cause, great. 

I will work on a solution for that. Unfortunately I have no retina display to test so I will need your help for that. 

I'll let you know as soon as I have News here...

JJ

**Comment by blutux** [comment]
No problem, let me know when (and where) I could test your fix . I will help you with pleasure (I'm also a developer, so I know that is not easy to have and to test all the possibilities ;) )

Blutux

**Comment by JamborJan** [comment]
Hi @blutux,

I found a solution. I have to build a new package now and will give it to you for testing. Unfortunately I have an issue with my key to sign the package. So you have to wait a bit. I hope to be ready tomorrow.

FYI: during testing the app a list of used files is generated for the build. Obviously the needed files for retina displays are not included while testing on a none-retina computer. That should be the reason.

**Comment by JamborJan** [comment]
Hi @blutux can you please test this package: https://github.com/JamborJan/paperwork/releases/tag/V7

You can download it and install it on your own instance for testing.

!!! Please don't use it in production yet. !!!

Thanks!

**Comment by blutux** [comment]
Ok, i will try this week end, because i have to save some notes before install it

**Comment by JamborJan** [comment]
You should be able to install it parallel as the app has another ID. But I would suggest to do a backup. Therefor you an download all grains one by one with the backup feature of sandstorm.

**Comment by funwhilelost** [comment]
I'm seeing the same issue on my retina MacBook and noticed it exhibits the same problem with the ckeditor icons (because they're loaded dynamically from JavaScript).  Hopefully you can test there.  The data coming back is unusual.  It comes back with a 404, Content-type: text/html, a Set-Cookie header, and a bunch of binary bytes in the body: `ï¿½ï¿½W[oï¿½6~Ï¯8ï¿½ï¿½ï¿½dï¿½qï¿½ï¿½ï¿½ï¿½Kï¿½ï¿½ï¿½ï¿½%ï¿½t...`

**Comment by JamborJan** [comment]
Hey @funwhilelost can you please check with this test release: https://github.com/JamborJan/paperwork/releases/tag/V7

I didn't find out so far how to test it without having a retina display. Please note that this is only for tests and not suitable for an update of all your grains.

Thanks!

**Comment by blutux** [comment]
Hi @JamborJan I have just done the backup, I have installed the beta package and it's works, I can see the icons with my macbook pro retina :)

**Comment by blutux** [comment]
@JamborJan Another things that i don't know if the new release will fix it, When i try to see a note, and after when i click on another note, the title change but not the content :( (if the new release will fix it, I will not open another issue, othewise I will open a new one

**Comment by JamborJan** [comment]
Hey @blutux I will keep this issue open until I'm able to deliver the release which fixes the issue.

Can you please open a ticket for the issue with the title / content of notes when switching? Please add also picture if possible as I'm not sure if you are talking about the list view or the edit view.

Thanks!

**Comment by JamborJan** [comment]
The issue has been solved. See https://github.com/JamborJan/paperwork/releases/tag/V7 or update via Sandstorm App Store.
