### ISSUE TITLE
Improve https / http detection (also for upstream)

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#4]
According to feedback from upstream dev: Could you try adding the if statement you've done in line 12 of routes.php and put it after line 39, remove it from where it is (or comment it), please? Make sure it is in App::before. Also replace the body of the if statement to make it like this: 
```
Request::setTrustedProxies([$request->getClientIp()]).
```
In other words, the code should be like this:
```
App::before(function($request)
{
// code
if ((array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) ? $_SERVER[ 'HTTP_X_FORWARDED_PROTO'] : 'HTTP_X_FORWARDED_PROTO not set') == "https") {
    /*$_SERVER['HTTPS'] = "on";
    URL::forceSchema('https');    */
        Request::setTrustedProxies([ $request->getClientIp()]);
}
// code
}
```

**Comment by JamborJan** [comment]
Comments from https://github.com/twostairs/paperwork/issues/281

I just flew over this issue, without spending as much thoughts on it as you guys did. Just a hint from my side: It's probably not the best solution if things like HTML::style needs to be replaced by a hardcoded link tag. In general, I would say that all this fixing should be done in Laravel, rather than within Paperwork, as it's the framework that needs to provide us with the HTTP_X_FORWARDED_PROTO feature.

I am currently working with JamborJan on a way to fix this issue as good and Laravel-friendly way as possible.

**Comment by JamborJan** [comment]
(External Feedback)

About http/https detection -- to me, this seems like something that we should make part of the vagrant-spk tooling. I just read through all the comments at https://github.com/twostairs/paperwork/issues/281 ; it's a fascinating issue. The more I read about it, and the more I think about it, the more uncertain I am of exactly where I would place a fix for it.

I wonder, though -- it seems to me that you should be able to get away with adding the following:

http://laravel-tricks.com/tricks/force-generation-of-http-https-link-if-behind-caching-server

perhaps to your config.php.

If that works, then maybe that's the simplest thing, and you can throw away your source code patches.

**Comment by JamborJan** [comment]
@Liongold I added in ```routes.php``` as suggested:

```
App::before(function($request)
{
    if ((array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) ? $_SERVER[ 'HTTP_X_FORWARDED_PROTO'] : 'HTTP_X_FORWARDED_PROTO not set') == "https") {
        Request::setTrustedProxies([ $request->getClientIp()]);
    }
});
```
This works as long as it is running in http but as soon as I am using https this error is shown:
```
0. Illuminate\Exception\Handler handleShutdown <#unknown>0
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class 'Symfony\Component\HttpFoundation\IpUtils' not found 
```
![iputils not found](https://cloud.githubusercontent.com/assets/7508960/8130247/3ba66118-1111-11e5-94ff-6d502f7eb820.png)

The ```HTML::style```have been restored as they are working correctly when ```HTTP_X_FORWARDED_PROTO``` is set.

The last remark which links to http://laravel-tricks.com/tricks/force-generation-of-http-https-link-if-behind-caching-server is also linked to the error shown in the picture above as both try to ```Request::setTrustedProxies(['127.0.0.1']);```.

I'll commit the changes I have done where you can see the changes. @Liongold let me know if I should test further things.

**Comment by JamborJan** [comment]
Hi @Liongold, I close that one on my side. If you have anything more to test, let me know.

**Comment by Liongold** [comment]
I'll take a look at this. Thank you very much and sorry for the late reply. Just to make it clear, what is not working now?

**Comment by JamborJan** [comment]
No worries, I didn't reply for ages myself. See this comment for the details about the error: https://github.com/JamborJan/paperwork/issues/4#issuecomment-111483596

And here commented the code snipped I used (of course with my part on top of that file commented): https://github.com/JamborJan/paperwork/blob/master/frontend/app/routes.php#L35-L43

**Comment by Liongold** [comment]
I'm not sure this will help. It's just the first thoughts I had. Can you try running composer dump-autoload? If that does not work, can you include `use Symfony/Component/HttpFoundation/` in the if statement before Request::setTrusted.....

**Comment by JamborJan** [comment]
I will check that during the next days. Thx.

**Comment by JamborJan** [comment]
Can only be tested when https://github.com/JamborJan/paperwork/issues/18 is working. Seems to be okay.

**Comment by Liongold** [comment]
OK, let me know when you have soem results.
