### ISSUE TITLE
Connect to Paperwork API

### ISSUE THREAD

**Issue by theSoenke** [JamborJan/paperwork#41]
Hi,

is it possible to connect to the Paperwork API from outside sandstorm?
I'm developing an Android client for Paperwork and would like to support sandstorm
https://github.com/theSoenke/Paperwork-Android

I've tried to find some information in the sandstorm documentation and as far as i understood it need to be supported by paperwork.

Thanks

**Comment by JamborJan** [comment]
Hi, thanks for contributing to both Paperwork and Sandstorm.

You are right, there needs to be stuff done on my side. I need to connect the Paperwork API inside the Sandstorm package with Sandstorms Cap'n'Proto to connect to the outside world or let the outside world in via an API. 

Unfortunately my workload is quite high at the moment and I cannot promise when this will be done. For one part of this task I'm waiting for feedback from Sandstorm devs here: https://github.com/sandstorm-io/sandstorm/issues/1648

My suggestion to unblock you from developing the app is to create a first version which only connects to normal Paperwork instances.

Please also note that the Paperwork team is working on a new version. Maybe you want to get in contact with @mrusme ([Twitter @mrusme](https://twitter.com/mrusme)) and check if you can join forces?

I hope this helps at least a bit.

**Comment by theSoenke** [comment]
Thanks for your answer.
The app already does work for normal sandstorm instances, but there are still quite a few things that can be improved in the meantime :)

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
