### ISSUE TITLE
share access problem in sandstorm

### ISSUE THREAD

**Issue by germakoci** [JamborJan/paperwork#42]
when sharing access other then Owner (Add Edit or Read), the other users only see a blank page, the application is not loading

**Comment by JamborJan** [comment]
Thanks for bringing up the issue. I guess I found the root cause and will fix it.

Detail: when saving a note / notebook I have to automatically save permissions for the dummy users as there is a sharing model within paperwork which we have disabled.

Work is in progress to solve the issue.

**Comment by JamborJan** [comment]
The blank screen was an issue in the automated login process which didn't work for none admins. This is solved.

Now I still have to find a way of always sharing new notes to users according to their permissions. As Paperwork has an own sharing model which is disabled in Sandstorm mode this is not as easy as I thought. Work continues ...

**Comment by JamborJan** [comment]
Not sure if this still is an issue. We have been testing a bit but not so much with sharing. Please let me know if there still is an issue.
