### ISSUE TITLE
loading problem in sandstorm

### ISSUE THREAD

**Issue by germakoci** [JamborJan/paperwork#43]
multiple users of the same grain have the problem of loading PaperWork, it remains hanging for a long time

as owner I can Restart App (doing so every day) but for the users it is either simply not loading at all, or showing it's loading for a long time and then doing nothing 

here a pic of how it looks like when the loading is finishing in most of the cases [strange, it has a watermark with DEMO VERSION that I as an owner don't see]

![screen-grain_access](https://cloud.githubusercontent.com/assets/7823491/16264109/e4fc20d4-3877-11e6-9631-99110a63c74e.png)

**Comment by JamborJan** [comment]
Hi @germakoci that is super strange, I never ever have seen `DEMO VERSION` and there is nothing in the code displaying this. Where are you running the grain? On https://oasis.sandstorm.io? If yes: what type of account do you have? maybe your free account is full and thats the reason?

Thanks for some more details.

**Comment by JamborJan** [comment]
Please let me also know the size of the grain. You find that info right next to the name:

![bildschirmfoto 2016-06-24 um 21 55 26](https://cloud.githubusercontent.com/assets/7508960/16349019/6cd9cb5c-3a56-11e6-8949-d9264d60472d.png)

I'm sometimes experiencing issues starting up the grain, then it takes a long time. Maybe it's related to the size.

**Comment by germakoci** [comment]
size of the grain is 26 MB,  it's just at the beginning

**Comment by germakoci** [comment]
@JamborJan the screenshot uploaded above, with the DEMO watermark is from a user in our group using sandstorm for work (non-free trial) hosted on our own server

**Comment by JamborJan** [comment]
So I guess the DEMO watermark must be connected somehow to the sandstorm for work license.

The loading issus is currently under investigation, will let you know as soon as I have news.

**Comment by JamborJan** [comment]
Current status: the loading issue is quite a problem: it behaves every time different. Maybe the reason is a combination of Paperwork in the current version not being the cleanest and best developed application and Sandstorm not being out of beta yet. Very weird scenarios. I will have to make further tests maybe it helps when I switch from the mysql db which is included to something better for Sandstorm like sqllite. This will take some time here. Update will be publishes as soon as there are news.

**Comment by JamborJan** [comment]
Hi @germakoci 

I did some improvements and also included the latest Paperwork version. When testing on https://oasis.sandstorm.io I get some good results with spin up time of a grain less than 10 seconds and grain size more than 40MB.

Can you please check with the pre release  v8 if you have also better results? Please backup your grains before just in case something doesn't go right during the upgrade. Then upload this spk: https://github.com/JamborJan/paperwork/releases/download/V8/paperworkV8_beta.spk

Please note that not all issues have been solved yet. The pre release v8 should still be better than the current version 7.

Please let me know the results and if this issue can be closed or not.

**Comment by JamborJan** [comment]
I have submitted a new version to the sandstorm app store. I was not able to recreate this issue anymore. The main thing I did to solve or at lease mitigate this is an update of the upstream Paperwork. Please let me know if there are any further issues.
