### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#44]
## Workaround

It seems that the upload dialogue is not stable. just in case you cannot upload a file try to drag & drop it. This usually works fine.

![untitled](https://cloud.githubusercontent.com/assets/7508960/16355820/8043270c-3ac3-11e6-8983-a340589f8c62.gif)

As described here: https://github.com/twostairs/paperwork/issues/580

Needs to be tested and issues / instability solved.

Pre-Release V8 with latest Paperwork upstream code has the issue also.

**Comment by JamborJan** [comment]
Hi @germakoci, one question: the new paperwork version has a limit for attachments for one note. Default is 10, do you think thats a good value or should this be increased?

**Comment by germakoci** [comment]
@JamborJan we don't really use attachments to notes, what we do we crosslink with a Davros repository for files

so 10 as a limit should be really enough, because in Sandstorm one can combine the different apps to add more docs to the note

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
