### ISSUE TITLE
Unable to delete Notebook (CSS bug?)

### ISSUE THREAD

**Issue by xarinatan** [JamborJan/paperwork#47]
I can't seem to delete notebooks.
If I open any notebook and select edit->Delete Notebook, the UI 'freezes' and if I open it up with the developer tools, I see an invisible div popped up in front that's called 'modalNotebookDelete' without any styling.
I really enjoy the Paperwork app so far, it would be really nice to have this fixed so I can delete my testing notebook with garbage notes 😃

**Comment by JamborJan** [comment]
Hi @xarinatan,

sorry for the late reply. Here is a short workaround to delete the notebook anyway:
![untitled](https://cloud.githubusercontent.com/assets/7508960/22368558/68d996f0-e487-11e6-9bde-0d930f8ef3c7.gif)

Thanks for taking time to open an issue. I will take a look at it and solve it as soon as possible. As far as I can see now it's an upstream issue and I have to check with the core developers.

**Comment by xarinatan** [comment]
All of my upvotes! Thank you for the workaround, I hadn't noticed that you could reach the interface through there yet :) 
Good luck with the bug hunting! Thanks for the help!

**Comment by JamborJan** [comment]
New release has been build and submitted to the sandstorm app store. Thanks to all involved for your help and testing. Thumbs up!
