### ISSUE TITLE
PDF Upload Error on Sandstorm

### ISSUE THREAD

**Issue by jessica613lyn** [JamborJan/paperwork#48]
Upload Error
-------------
It looks like I am coming up with an error when I try to attach a .pdf in Sandstorm. The file attempts to upload, but quickly fails. I tried dragging the file as well as using the upload button and neither worked. I have also tried with multiple .pdf files.

![bug report video](https://cloud.githubusercontent.com/assets/26339314/23820937/e3cb607a-05e1-11e7-9210-ebe735744b38.gif)

**Comment by JamborJan** [comment]
Thanks for submitting the issue. I'll investigate asap and let you know when it is solved.

**Comment by JamborJan** [comment]
Hey @jessica613lyn I have been investigating and the complete broken upload seems to be solved. I can now upload via drag & drop but when using the upload document button a strange issue occurs which I have send to the upstream developers (see https://github.com/twostairs/paperwork/issues/782). I currently think it is not an sandstorm issue.

Can I kindly ask you to check if you can work with the new pre-release? You can download the SPK here: https://github.com/JamborJan/paperwork/releases/tag/v9. Please ensure that you backup all grains before you update them. If there are any questions or further issues please let me know.

Thanks again for taking the time to raise the issue. Much appreciated.

**Comment by spankito** [comment]
Same issue here.

Just tested last spk pre-release and it worked for me.
![attachment](https://cloud.githubusercontent.com/assets/2588913/24401551/27fce044-13b5-11e7-8db2-8bf399f3aff2.jpg)

**Comment by JamborJan** [comment]
thanks @spankito for testing, I just wait a bit for @jessica613lyn in case there is an issue and then I push the update to the app market.

**Comment by mr9v9** [comment]
@JamborJan So did this ever get updated on the Sandstorm App? I tried the upload today and it is still broken for me.

**Comment by JamborJan** [comment]
Hey @mr9v9 , sorry that seems to get lost. Will try to check and push it to the store on the weekend.

**Comment by mr9v9** [comment]
Thanks @JamborJan BTW I tested that pre-release and it seems to be working over here.

**Comment by JamborJan** [comment]
New release has been build and submitted to the sandstorm app store. Thanks to all involved for your help and testing. Thumbs up!
