### ISSUE TITLE
Merge from docker to vagrant build process

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#8]
As sandstorm is building a vagrant app creation tool I merge the package to that.

See:
https://github.com/zarvox/vagrant-spk +
https://github.com/sandstorm-io/sandstorm/wiki/Porting-an-app-with-vagrant-spk

**Comment by JamborJan** [comment]
Current status:
- basic setup done & config done
- Config needs to be double checked for errors, e.g.

```
==> default: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysqld.sock' (2)
==> default: php5-fpm stop/waiting
==> default:  * Stopping MariaDB database server mysqld
==> default:    ...fail!
```

**Comment by JamborJan** [comment]
Hey @paulproteus just in case you have a chance to help me ...

I have tried to setup my Paperwork port with Vagrant just like I did it for the ownCloud stuff and like it is described in the examples. But unfortunately only this is not working. I bet I have a very small typo or config mess up but I'm too blind to find it.

The result is, that I cannot open ```http://localhost:6080``` after ```vagrant-spk up``` and ```vagrant-spk dev```.

If you are able to help me with your experience with Vagrant and give me a hind that would be awesome, I don't expect you to analyze and debug the stuff.

**Comment by paulproteus** [comment]
Will look into this today! Also cc: @zarvox

**Comment by JamborJan** [comment]
Again: I'm not sure if I'm stupid or what the reason is. If you see something, say something :-)

**Comment by JamborJan** [comment]
Hey @paulproteus and @zarvox,

can one of you help me with that stuff. When you git clone this repo and use the vagrant-spk you should get the app running. But unfortunately I only get **500: Internal Server Error**.

I'm experimenting since some days with the stuff and faced several stupid misconfiguration things from my side. Now I think I'm too blind to see the solution and really hope that one of you guys can help me here.

Thanks a lot!
JJ

**Comment by zarvox** [comment]
Apologies for letting this fall off my radar for too long, and thanks for pinging again.

I tried running the git clone, and got the same 500 error you mentioned.

`vagrant-spk ssh` will drop you into a shell in the Vagrant VM.  Looking in `/opt/sandstorm/var/sandstorm/grains/`, I see in `<grainId>/sandbox/log/nginx/error.log`:

2015/05/26 20:50:24 [error] 69#0: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/opt/app/frontend/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/app/frontend/bootstrap/autoload.php on line 17                 
PHP message: PHP Fatal error:  require(): Failed opening required '/opt/app/frontend/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/app/frontend/bootstrap/autoload.php on line 17" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "n0dycxywsss2fwwup28f.local.sandstorm.io:6080"

This suggests to me that paperwork is looking for composer-provided modules.  However, I don't see any checked into the repo, and while there's a `composer.phar`, I don't see a `composer.json` specifying dependencies to fetch/download/use.

Once you've added the requisite composer.json, replacing your `.sandstorm/build.sh` with https://github.com/zarvox/vagrant-spk/blob/master/vagrant-spk#L205 will make sure composer runs when you do `vagrant-spk dev`.

I think that should get you moving on the right track - feel free to ping again if anything else seems awry, and I'll do my best to give a better turnaround. :)

**Comment by zarvox** [comment]
Oh, I spoke slightly too soon -- I see now that there *is* a `composer.json` in the `frontend/` folder.  I'd suggest adjusting your `.sandstorm/build.sh` as before to call composer.  If you use the script embedded in vagrant-spk, you might need to adjust the paths for the conditionals (or ignore them entirely, since you know what the appropriate build steps will be for your app :) ).

**Comment by zarvox** [comment]
Poking at this a little longer, I wound up able to run a grain (new errors, but hey, progress!) with the following:

`build.sh`:
```bash
#!/bin/bash
set -eu
cd /opt/app/frontend
php ../composer.phar install
```

In `setup.sh`, I needed to modify a couple lines to also install php5-cli, php5-dev, php5-gd, php5-mcrypt, and enable the mcrypt module:
```diff
diff --git a/.sandstorm/setup.sh b/.sandstorm/setup.sh
index def914e..5bd0afb 100644
--- a/.sandstorm/setup.sh
+++ b/.sandstorm/setup.sh
@@ -1,7 +1,8 @@
 #!/bin/bash
 export DEBIAN_FRONTEND=noninteractive
 apt-get update
-apt-get install -y nginx php5-fpm php5-mysql mysql-server
+apt-get install -y nginx php5-fpm php5-mysql php5-cli php5-dev php5-gd php5-mcrypt mysql-server
+sudo php5enmod mcrypt
 sudo unlink /etc/nginx/sites-enabled/default
 cat > /etc/nginx/sites-available/sandstorm-php <<EOF
 server {
```

**Comment by JamborJan** [comment]
Hi @zarvox ,

Thanks so much! The ```build.sh``` was the solution, ```setup.sh``` was unfortunately broken due to my 1'000 different tests before.

The error messages you mention are due to the fact that I have moved the folders where the app should store data to ```/var``` which is now not working any longer apparently. Will check that next.

**Comment by JamborJan** [comment]
Hey @zarvox do you mind if I bother you again. I have an issue with moving folders to ```/var``` which need to be writable and sandstorm requires writable folders to be there.

For paperwork the folder ```/opt/app/frontend/app/storage``` needs to be writable. So what I did also before when I used the Docker build process is I created the folder including sub folders in ```/var``` and symlinked this to ```/opt/app/frontend/app/storage```. With my old build process via docker this worked well, now it seems not to work and I'm either too blind to find the reason or it might be an issue with the vagrant-spk, not sure.

I tested a bunch of different things and at the moment the whol stuff is added here https://github.com/JamborJan/paperwork/blob/master/.sandstorm/build.sh#L19-L40

Do you mind if you take a look at this and help me once again?

**Comment by zarvox** [comment]
No worries!  I'm always happy to help.

I should probably document the following in the README, but:
  * `setup.sh` is intended for getting things that are system-global packages, or language package managers, or build tools, or daemons that you use directly from upstream
  * `build.sh` is intended for doing app-specific build tasks, like installing app-s
  * `launcher.sh` is your entry point for running your service in the Sandstorm sandbox.  Here's where you'd do any app-specific, per-grain setup, including anything that deals with /var.

So I think you probably want to create those subfolders under /var/ in `.sandstorm/launcher.sh`, not `.sandstorm/build.sh`.  The sandstorm app, on first launch, gets a completely empty /var, and it's up to you to populate that with what your app expects.  FWIW, in launcher.sh, you shouldn't need sudo to create that folder tree.

On the topic of folders and sometimes needing to copy them from the readonly image: I'm somewhat interested in the possibility of using systemd to supervise multi-process containers, or set up empty folders or things to be copied in from `/usr` via [systemd-tmpfiles](http://www.freedesktop.org/software/systemd/man/systemd-tmpfiles.html), but systemd itself doesn't seem to like running unprivileged in a user namespace.

**Comment by zarvox** [comment]
To be absolutely clear: anything you do that touches `/var` should probably happen in `launcher.sh`  The one exception will be setting up symlinks from `/opt/app/*` to places under `/var` since /opt/app will be readonly from inside the sandbox.  (Yes, `/opt/app/frontend/app/storage` will look like a broken symlink from the view outside of the sandbox, but whenever the app is running in the sandbox, it'll see `/var/storage`, since your `launcher.sh` will create those folders then.)

So keep the `ln -s` in `build.sh`, but move the `cp` and the `mkdir`s and the `chmod` (if still needed) to `launcher.sh`

**Comment by paulproteus** [comment]
(As a random bystander, let me say) this conversation suggests to me that
we should start using the "grain" terminology in vagrant-spk.

Regardless of that, I'm glad you two are working on this and working
through these issues.
​

**Comment by JamborJan** [comment]
Hi @zarvox, I understand what you are saying and changed ```build.sh``` and ```launcher.sh```.

The situation is anyway not changed: the grain starts up and the app is still not able to find the json file which should be located in ```/var/storage/meta```. How can I look into the sandbox if everything is right there with the folders, json files and the link?

I'm a bit embarrassed that I'm not able to setup a simple link of a folder making this stuff work. Also taking into account that it is working when I do it with the former docker build process I used.

Do you have any chance to pull this repo once again and take a look at the situation when you do ```vagrant-spk dev```?

**Comment by zarvox** [comment]
Hi @JamborJan 

You're pretty close!  It looks like Laravel needs a slightly different nginx conf, since the app is entirely dispatched on the PHP side, rather than by the browser.  I followed the advice at http://laravel.com/docs/5.0/installation#pretty-urls to get an nginx conf file that works - patch that into `setup.sh`.

```diff
-        try_files \$uri \$uri/ =404;
+        try_files \$uri \$uri/ /index.php?$query_string;
```

From there, it seemed like the DB setup wasn't quite right, so I applied:

```diff
diff --git a/.sandstorm/launcher.sh b/.sandstorm/launcher.sh
index 929bfc3..7cd68c7 100755
--- a/.sandstorm/launcher.sh
+++ b/.sandstorm/launcher.sh
@@ -12,6 +12,17 @@ rm -rf /var/run
 mkdir -p /var/run
 mkdir -p /var/run/mysqld
 
+# move storage folders which must be writable to /var
+rm -rf /var/storage
+mkdir -p /var/storage
+mkdir -p /var/storage/attachments
+mkdir -p /var/storage/cache
+mkdir -p /var/storage/logs
+mkdir -p /var/storage/meta
+mkdir -p /var/storage/sessions
+mkdir -p /var/storage/views
+cp /opt/app/services.json /var/storage/meta/services.json
+
 # Ensure mysql tables created
 HOME=/etc/mysql /usr/bin/mysql_install_db --force
 
@@ -28,16 +39,12 @@ while [ ! -e /var/run/php5-fpm.sock ] ; do
     sleep .2
 done
 
+# Ensure the paperwork database exists.
+echo "CREATE DATABASE IF NOT EXISTS paperwork DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;" | mysql --user root --socket /var/run/mysqld/mysqld.sock
+
+# Run database migrations.
+time php /opt/app/frontend/artisan migrate --force
+
 # Start nginx.
 /usr/sbin/nginx -g "daemon off;"
 
-# move storage folders which must be writable to /var
-rm -rf /var/storage
-mkdir -p /var/storage
-mkdir -p /var/storage/attachments
-mkdir -p /var/storage/cache
-mkdir -p /var/storage/logs
-mkdir -p /var/storage/meta
-mkdir -p /var/storage/sessions
-mkdir -p /var/storage/views
-cp /opt/app/services.json /var/storage/meta/services.json
```

Note that I moved the stuff setting up `/var/storage` to *before* we start PHP, since it'll need to be in place by the time php5-fpm receives the first request.

From there, we have a database, but our frontend isn't in good shape.  Looking at the official instructions at https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Debian-7 it looks like there are some nodejs and bower things.  I notice your repo is missing `bower.json`, whereas upstream has it: https://github.com/twostairs/paperwork/blob/master/frontend/bower.json - perhaps you need to rebase?

Anyway, after all that, I'm looking at an app that's in decent shape, but needs frontend fixing.  I imagine getting the npm/bower/gulp stuff sorted out will fix this:

![snapshot1](https://cloud.githubusercontent.com/assets/307325/7905781/a3799acc-07d3-11e5-8608-c82fea4d756f.png)

Getting closer!

**Comment by JamborJan** [comment]
Thanks @zarvox 

I will continue to work in that. Only FYI: the step ensure the paperwork database exists in ```launcher.sh``` worked only with a slightly different SQL statement for me:

```
CREATE DATABASE IF NOT EXISTS paperwork DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL PRIVILEGES ON paperwork.* TO 'paperwork'@'localhost' IDENTIFIED BY 'paperwork' WITH GRANT OPTION; FLUSH PRIVILEGES;
```
This one was used by me before and was part of the Paperwork docs (at least in the past).

Thanks a lot for all your help!

**Comment by zarvox** [comment]
Oh yeah, that's even better.  I changed the settings file to use user root and empty password, since that's what vagrant-spk exposes by default, but what you did is perfectly fine and means less delta against upstream configs.

**Comment by JamborJan** [comment]
FYI and thanks a lot @zarvox!
![bildschirmfoto 2015-06-02 um 20 44 54](https://cloud.githubusercontent.com/assets/7508960/7944096/f542a132-0968-11e5-9355-dabcd2f4d876.png)
